# Generated by Django 4.1.13 on 2026-02-27 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('length', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'tailorhub_customer',
            },
        ),
        migrations.CreateModel(
            name='TailorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(default='Shirt', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], default='Pending', max_length=50)),
                ('order_date', models.CharField(blank=True, default='', max_length=50)),
                ('estimated_completion_date', models.CharField(blank=True, default='', max_length=50)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.customer')),
            ],
            options={
                'db_table': 'tailorhub_order',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(choices=[('Shirt', 'Shirt'), ('Pant', 'Pant'), ('Koti', 'Koti'), ('Suit', 'Suit'), ('Jabbho', 'Jabbho'), ('Lehngho', 'Lehngho'), ('Safari', 'Safari'), ('Jodhpuri', 'Jodhpuri')], default='Shirt', max_length=50)),
                ('length', models.CharField(blank=True, default='', max_length=20)),
                ('chest', models.CharField(blank=True, default='', max_length=20)),
                ('waist', models.CharField(blank=True, default='', max_length=20)),
                ('collar', models.CharField(blank=True, default='', max_length=20)),
                ('shoulder', models.CharField(blank=True, default='', max_length=20)),
                ('sleeve', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.customer')),
            ],
            options={
                'db_table': 'tailorhub_measurements',
            },
        ),
    ]
