# Generated by Django 4.1.13 on 2026-03-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='hip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='measurement',
            name='rise',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
